_BASE_: "./Base_RFCOS_EARL_R50.yaml"
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/FAIR/R-50-GN"
  RESNETS:
    STRIDE_IN_1X1: False
    NORM: "GN"
  FPN:
    NORM: "GN"
  RFCOS:
    NORM: "GN"
    TOPK_SAMPLE: 14
    ANGLE_RANGE: "a180"
    NMS_THRESH_TEST: 0.4
    BBOX_REG_LOSS_TYPE: "smooth_l1_weight"
DATASETS:
  TRAIN: ("DIOR_trainval", )
  TEST: ("DIOR_test",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.045
  STEPS: (13000, 17500)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "./work_dir/DIOR_R/EARL_VAF_R50_800_bs64"